### ISSUE TITLE
How can uninstall?

### ISSUE THREAD

**Issue by ArthurMenezes** [polterguy/hyper-ide#1]
I installed this on my ubuntu16.04LTS with install.sh script. I want to remove, how do I?

**Comment by polterguy** [comment]
Hi Arthur, just delete the contents of your `/var/www/html` folder, and edit your `/etc/apache2/apache2.conf` file, and remove everything beneath where it says _"Phosphorus Five"_, then restart apache with `sudo service apache2 restart`, and that should do the trick :)

In addition, it installed also mono, MySQL and GnuPG. You can uninstall these modules with `apt-get` shell commands ...

**Comment by polterguy** [comment]
Did it work ...?

I'll just close this one, unless you choose to reopen it :)
